pipeline {
        agent any
        stages {
                stage ('build'){
                        steps {
                                echo "this is building step"
                        }
                }
                stage ('test'){
                        steps {
                                echo "this is testing step"
                        } 
                        
                }
                stage ('deploy'){
                        steps {
                                echo "this is deploying step"
                        }
                }
        
        }
}
